name: Deploy

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: abfuhrtermine
          package: '.'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-funcignore: true
          scm-do-build-during-deployment: true
          enable-oryx-build: true
